apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.form: |
    url: https://37f4-2a0d-6fc2-66d2-e000-e9-b7fd-9593-7676.eu.ngrok.io
  template.form-data: |
    webhook:
      form:
        method: POST
        path: /event/argocd
        body: |
          {
            "test": "pasha"
          }