apiVersion: batch/v1
kind: Job
metadata:
  name: validate-infra
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: validate
          image: curlimages/curl
#          command:
#            - "curl"
#            - "--help"
          command:
            - "curl"
            - "--fail-with-body"
            - "-H"
            - "Content-Type: application/x-www-form-urlencoded"
            - "-X"
            - "POST"
            - "-d"
            - "app=infra&owner=itai-project-one&repo=infra"
            - "https://37f4-2a0d-6fc2-66d2-e000-e9-b7fd-9593-7676.eu.ngrok.io/operations/validate"
      restartPolicy: Never
  backoffLimit: 0
